### PR TITLE
Add option to select libmariadb/libmysql

### PR DESCRIPTION
**Pull request by ranisalt**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Adds a CMake option to toggle between libmariadb (default) and libmysql. Using `default-features` is broken because it's impossible to _remove_ from the array, so selecting `libmysql` would cause _both_ to be installed - which is impossible because they conflict in install paths.

**Issues addressed:** failing builds in #4937 

**How to test:** 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by NRH-AA** [comment]
Boo MySQL woo MariaDB

**Comment by ranisalt** [comment]
> Boo MySQL woo MariaDB

Agreed, but with libmariadb borked in vcpkg it's the only way. Technically both clients can access both servers, I can use a MariaDB server with libmysql client libs 😆

**Comment by gesior** [comment]
It switched library used by vcpkg to `libmysql` (`cmake --preset vcpkg -DUSE_LIBMYSQL=ON`), but this lib also fails to build with current Linux vcpkg instruction 😞 
Error `vcpkg/buildtrees/libmysql/config-x64-linux-out.log`:
```
-- Checking for module 'libtirpc'
--   Package 'libtirpc', required by 'virtual:world', not found
CMake Warning at cmake/rpc.cmake:41 (MESSAGE):
  Cannot find RPC development libraries.  You need to install the required
  packages:

    Debian/Ubuntu:              apt install libtirpc-dev
    RedHat/Fedora/Oracle Linux: yum install libtirpc-devel
    SuSE:                       zypper install glibc-devel
```

I tried to run recommended `apt install libtirpc-dev`, but then it failed with errors like.
Error `vcpkg/buildtrees/libmysql/install-x64-linux-dbg-out.log`:
```
FAILED: extra/libedit/libedit-20221030-3.1/src/CMakeFiles/edit.dir/terminal.c.o
/usr/bin/cc -DBOOST_NO_CXX98_FUNCTION_BASE -DLZ4_DISABLE_DEPRECATE_WARNINGS -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_USE_MATH_DEFINES -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/root/vcpkg/buildtrees/libmysql/src/sql-8.0.40->/root/vcpkg/buildtrees/libmysql/src/sql-8.0.40-c2be1ae70a.clean/extra/libedit/libedit-20221030-3.1/src/terminal.c: In function  ^`^xterminal_move_to_line ^`^y:
/root/vcpkg/buildtrees/libmysql/src/sql-8.0.40-c2be1ae70a.clean/extra/libedit/libedit-20221030-3.1/src/terminal.c:518:44: error: implicit declaration of function  ^`^xtgoto ^`^y [-Wimplicit-function-declaration]
  518 |                         terminal_tputs(el, tgoto(Str(T_UP), -del, -del), -del);
      |                                            ^~~~~
/root/vcpkg/buildtrees/libmysql/src/sql-8.0.40-c2be1ae70a.clean/extra/libedit/libedit-20221030-3.1/src/terminal.c:518:44: error: passing argument 2 of  ^`^xterminal_tputs ^`^y makes pointer from integer without a cast [-Wint-co>  518 |                         terminal_tputs(el, tgoto(Str(T_UP), -del, -del), -del);
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            int
/root/vcpkg/buildtrees/libmysql/src/sql-8.0.40-c2be1ae70a.clean/extra/libedit/libedit-20221030-3.1/src/terminal.c:212:44: note: expected  ^`^xconst char * ^`^y but argument is of type  ^`^xint ^`^y
  212 | static void     terminal_tputs(EditLine *, const char *, int);
```

Maybe current vcpkg version cannot work with C++23 compiler like g++ 15.

**Comment by ranisalt** [comment]
It works fine on Arch selecting libmysql

**Comment by gesior** [comment]
> It works fine on Arch selecting libmysql

It's hard to say, as Arch updates so often.
What Arch version do you use?
I used latest, probably `docker pull archlinux:multilib-devel-20250629.0.373469` or `docker pull archlinux` for tests.
I'm not sure, if keeping Arch compatible makes sense, as it releases distro every month/day:
https://archlinux.org/releng/releases/

If you want to post any error on Arch, post `Dockerfile` for that distro with vcpkg build.

**Comment by alysonjacomin** [comment]
@ranisalt @gesior It is a great option to merge this PR and the PR #4971, both complement each other

**Comment by gesior** [comment]
> @ranisalt @gesior It is a great option to merge this PR and the PR #4971, both complement each other

I think they fix the same problem in 2 different ways, so we can merge only one.
- #4971 PR: detects database connector version that has problems with connection to MySQL/MariaDB server and adds C++ code to force SSL off
- This PR:  let user choose between MySQL/MariaDB C++ connector library, so he can pick one that works for him - I'm not sure, if it works with every possible scenario (edge case: it does not change anything on Linux with system libs? if I install wrong [mysql or mariadb], it will still pick it, compile and fail to start]

Linux build with system libraries already has code that auto-picks MySQL/MariaDB library:
https://github.com/otland/forgottenserver/blob/f169c6c3dc0d3f1f20ce09d3fdc32c81b05794ca/cmake/FindMySQL.cmake
With this PR, no matter what I pick, it will go into:
https://github.com/otland/forgottenserver/pull/4938/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR76
or:
https://github.com/otland/forgottenserver/pull/4938/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR83
and use library which it detects first, not library I set with `USE_LIBMYSQL` `ON/OFF`.

**I need to prepare few dockers to test all these builds and if it connects to database on startup.**

**Comment by ranisalt** [comment]
No, the two PRs are orthogonal. This PR merely let's you choose whether vcpkg will install libmariadb or libmysql, with the former being broken and not working with GCC 15+ - we can't fix it, the error is in external code. The `find_package(MySQL)` line does **NOT** force libmysql, in some systems the libmariadb package will be aliased to libmysql because they are compatible, it's just a fallback name that will use the `FindMySQL` script

**Comment by gesior** [comment]
> This PR merely let's you choose whether vcpkg will install libmariadb or libmysql, with the former being broken and not working with GCC 15+ - we can't fix it,

Yea. I forgot about that problem and I did not think it may be fixed with this code, but it probably is.
@alysoncode You were right. We should merge both PRs as different problems fixes.

> line does **NOT** force libmysql, in some systems the libmariadb package will be aliased to libmysql because they are compatible

**Code-style note**
It does not force this on Linux and this is a bit confusing with current code.
Variable name `USE_LIBMYSQL` and/or text `Use libmysql instead of libmariadb` should somehow notice user, that it will be forced only, if he uses VCPKG build.

---

**What I already tested (by 'build' I mean compile and start OTS):**
- Ubuntu 24.04 builds (mysql/mariadb) with system libraries - works
- Windows builds with vcpkg and Visual Studio - mariadb fails without #4971 

**What left to test:**
- dockers that run MySQL 8.0 server in place of MariaDB 10.x - make sure it works with MySQL server
- vcpkg builds on Ubuntu 24.04 with mariadb/mysql
- vcpkg builds on Windows with cmake with mariadb/mysql
- vcpkg builds on Ubuntu 25.10 (g++ 15, C++23) with mariadb/mysql

**Tests progress:**

I made dockers that build and run TFS with system libraries, it looks like it works with MariaDB and MySQL connectors, but I have to verify it again later (print detected connector). I tested both connecting to MariaDB 10.x server. Tomorrow I will make dockers with MySQL 8.0.
Tomorrow I will prepare dockers for TFS build and run with vcpkg on Ubuntu 24.04.

**Comment by ranisalt** [comment]
> Variable name `USE_LIBMYSQL` and/or text `Use libmysql instead of libmariadb` should somehow notice user, that it will be forced only, if he uses VCPKG build.

Yeah, that's right. It's a bit hard to word that given the amount of possible scenarios. I'll update the message to make it clearer

**Comment by gesior** [comment]
@DSpeichert @ArturKnopik 
As `CMakeLists.txt` compiles with cmake on Windows and Linux, with and without vcpkg, it can't be much more readable than this PR.

I think we should merge this PR.
It should fix `g++-15` (C++23 -> Ubuntu 25.10 and Arch Linux builds) compilation and `cmake` compilation with `vcpkg`, if you run it with `cmake -DUSE_LIBMYSQL=ON`.

**Comment by ArturKnopik** [comment]
some note: c++23 is not supported by visual studio, there is only preview version

**Comment by gesior** [comment]
@ArturKnopik 
We don't set C++ to 23 anywhere in TFS, but g++ 15 reports C++23 "problems", when we build vcpkg libraries.

I did some tests in docker using Ubuntu:
- Ubuntu 24.04, g++ 13, **libmysql:** builds
- Ubuntu 24.04, g++ 13, **libmariadb**: builds
- Ubuntu 25.10, g++ 14, **libmysql**: **fails**
- Ubuntu 25.10, g++ 14, **libmariadb**: builds
- Ubuntu 25.10, g++ 15, **libmysql**: **fails**
- Ubuntu 25.10, g++ 15, **libmariadb**: **fails**

MySQL build errors:
```
[162/478] /usr/bin/cc -DBOOST_NO_CXX98_FUNCTION_BASE -DLZ4_DISABLE_DEPRECATE_WARNINGS -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_USE_MATH_DEFINES -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/root/vcpkg/buildtrees/libmysql/src/sql-8.0.40->
FAILED: extra/libedit/libedit-20221030-3.1/src/CMakeFiles/edit.dir/terminal.c.o
/usr/bin/cc -DBOOST_NO_CXX98_FUNCTION_BASE -DLZ4_DISABLE_DEPRECATE_WARNINGS -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_USE_MATH_DEFINES -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/root/vcpkg/buildtrees/libmysql/src/sql-8.0.40-c2be1ae70a>
/root/vcpkg/buildtrees/libmysql/src/sql-8.0.40-c2be1ae70a.clean/extra/libedit/libedit-20221030-3.1/src/terminal.c: In function  ^`^xterminal_move_to_line ^`^y:
/root/vcpkg/buildtrees/libmysql/src/sql-8.0.40-c2be1ae70a.clean/extra/libedit/libedit-20221030-3.1/src/terminal.c:518:44: error: implicit declaration of function  ^`^xtgoto ^`^y [-Wimplicit-function-declaration]
  518 |                         terminal_tputs(el, tgoto(Str(T_UP), -del, -del), -del);
```

MariaDB build errors:
```
[1/85] /usr/bin/cc -DHAVE_OPENSSL -DHAVE_TLS -DLIBICONV_PLUG -DMARIADB_MACHINE_TYPE=\"x86_64\" -DMARIADB_SYSTEM_TYPE=\"Linux\" -I/root/forgottenserver-master/build/vcpkg_installed/x64-linux/include -I/root/vcpkg/buildtrees/libmariadb/x64>
FAILED: libmariadb/CMakeFiles/mariadb_obj.dir/__/plugins/auth/mariadb_cleartext.c.o
/usr/bin/cc -DHAVE_OPENSSL -DHAVE_TLS -DLIBICONV_PLUG -DMARIADB_MACHINE_TYPE=\"x86_64\" -DMARIADB_SYSTEM_TYPE=\"Linux\" -I/root/forgottenserver-master/build/vcpkg_installed/x64-linux/include -I/root/vcpkg/buildtrees/libmariadb/x64-linux->
In file included from /root/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/plugins/auth/mariadb_cleartext.c:19:
/root/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/include/ma_global.h:687:25: error:  ^`^xbool ^`^y cannot be defined via  ^`^xtypedef ^`^y
```

Commands to build TFS master on Ubuntu 25.10 using g++ 15:
```bash
# run docker
docker run --rm -it ubuntu:25.10 /bin/bash

# inside docker
apt update && apt install -y git wget zip curl zip unzip tar cmake build-essential pkg-config ninja-build libtirpc-dev libldap2-dev libsasl2-dev libtirpc-dev g++-15 
rm /usr/bin/g++ /usr/bin/gcc && cp /usr/bin/g++-15 /usr/bin/g++ && cp /usr/bin/gcc-15 /usr/bin/gcc

git clone https://github.com/microsoft/vcpkg.git "$HOME/vcpkg"
cd "$HOME/vcpkg" && ./bootstrap-vcpkg.sh && ./vcpkg integrate install
export VCPKG_ROOT="$HOME/vcpkg"
cd ~
wget https://github.com/otland/forgottenserver/archive/refs/heads/master.zip
unzip master.zip && cd forgottenserver-master/
cmake --preset vcpkg
cmake --build --preset vcpkg --config Debug
```

**Comment by alysonjacomin** [comment]
So for now, we should wait to pin the last topic: "vcpkg builds on Ubuntu 25.10 (g++ 15, C++ 23) with mariadb/mysql."

I was looking here and Ranisalt has already prepared practically everything for this adaptation related to changes for C++23 in PR #4936, I'm right @ranisalt ?

If so, we can merge this PR #4938 and PR #4971, and then in the future, when Visual Studio has the necessary adaptations, we can consider this last case "vcpkg builds on Ubuntu 25.10 (g++ 15, C++ 23) with mariadb/mysql." mentioned by @gesior

**Comment by alysonjacomin** [comment]
```
> @ArturKnopik We don't set C++ to 23 anywhere in TFS, but g++ 15 reports C++23 "problems", when we build vcpkg libraries.
> 
> I did some tests in docker using Ubuntu:
> 
> * Ubuntu 24.04, g++ 13, **libmysql:** builds
> * Ubuntu 24.04, g++ 13, **libmariadb**: builds
> * Ubuntu 25.10, g++ 14, **libmysql**: **fails**
> * Ubuntu 25.10, g++ 14, **libmariadb**: builds
> * Ubuntu 25.10, g++ 15, **libmysql**: **fails**
> * Ubuntu 25.10, g++ 15, **libmariadb**: **fails**
```
If it is possible to make this compatible with the other versions it would be perfect for the current moment

**Comment by alysonjacomin** [comment]
@ranisalt  You mentioned in #4971 that this PR is necessary so that you can approve that PR.

Gesior mentioned compiling with C++23, but we can't do that yet because Visual Studio doesn't offer that support.

Considering that the connection is broken without PR #4971, shouldn't we merge this PR and PR #4971 right away ? Considering that we can't offer that support for C++23 yet

**Review by DSpeichert — APPROVED** [review]
