### PR TITLE
Cast system, 10.99 support and premium display in character list fix.

### PR DESCRIPTION
**Pull request by Milice**
I have added a cast system fully compatible with tfs 1.3, with multiple chat commands including but not limited to /kick, /togglechat, /ban, etc.

I also have changed the definitions to support login with the 10.99 client thus also the Tibia 11 client (i have released a functioning webscript for this on OTLand), and i noticed that the premium days weren't displaying properly in the character list so i also provided a fix for this.

### CODE REVIEW

**Comment by DSpeichert** [comment]
You should split this PR into separate: cast system, 10.99 and other fixes.
Don't include "reverts" and merges that are not relevant to the upstream repository (this one).
That will help your PR get reviewed faster/easier.

File: src/protocolgame.cpp [hunk 1]
```diff
@@ -366,8 +371,13 @@ void ProtocolGame::disconnectClient(const std::string& message) const
 	disconnect();
 }
 
-void ProtocolGame::writeToOutputBuffer(const NetworkMessage& msg)
+void ProtocolGame::writeToOutputBuffer(const NetworkMessage& msg, bool broadcast/* = true*/)
 {
+	if(broadcast && player->isLiveCasting()) {
+		for(auto& spectator : player->spectators) {
+				spectator->writeToOutputBuffer(msg, false);
```
Comment (djarek) [inline src/protocolgame.cpp]: I don't think this solution will be accepted https://github.com/otland/forgottenserver/issues/984#issue-42451810 - the work of broadcasting is done in the dispatcher thread.

File: src/iologindata.cpp [hunk 2]
```diff
@@ -160,6 +160,35 @@ uint32_t IOLoginData::gameworldAuthentication(const std::string& accountName, co
...
 }
 
+std::list<std::string> IOLoginData::liveCastAuthentication(const std::string& password)
+{
+	std::list<std::string> casts;
+
+	Database* db = Database::getInstance();
+
+	std::ostringstream query;
+	query << "SELECT `player_id`, `name`, `password`, `spectators` FROM `live_casts` WHERE `password` = '" << password << "'";
```
Comment (djarek) [inline src/iologindata.cpp]: Plaintext passwords are bad, even if they are only temporary.

File: src/iologindata.cpp [hunk 3]
```diff
@@ -160,6 +160,35 @@ uint32_t IOLoginData::gameworldAuthentication(const std::string& accountName, co
 	return accountId;
 }
 
+std::list<std::string> IOLoginData::liveCastAuthentication(const std::string& password)
```
Comment (djarek) [inline src/iologindata.cpp]: std::list is an extremely wasteful container for std::strings.

File: src/iologindata.cpp [hunk 4]
```diff
@@ -160,6 +160,35 @@ uint32_t IOLoginData::gameworldAuthentication(const std::string& accountName, co
...
+
+	std::ostringstream query;
+	query << "SELECT `player_id`, `name`, `password`, `spectators` FROM `live_casts` WHERE `password` = '" << password << "'";
+	DBResult_ptr result = db->storeQuery(query.str());
+	if (!result) {
+		return casts;
+	}
+
+	query.str(std::string());
+	query << "SELECT `name` FROM `live_casts` WHERE `password` = '" << password << "' ORDER BY `name` ASC";
```
Comment (djarek) [inline src/iologindata.cpp]: Why are you touching the the same database table twice in the same function? TBH I don't see why you would even need to check the database at all to log in a spectator.

File: src/player.h [hunk 5]
```diff
@@ -1182,6 +1239,9 @@ class Player final : public Creature, public Cylinder
 		std::map<uint32_t, int32_t> storageMap;
 
 		std::vector<OutfitEntry> outfits;
+		std::vector<ProtocolSpectator*> spectators;
```
Comment (djarek) [inline src/player.h]: I don't think it's safe to store raw pointers to objects managed by shared_ptrs (unless you can guarantee their lifetimes).

**Comment by Milice** [comment]
Thank you a lot @djarek for all your pointers, i shall close this and try again for i would love for the official repository to have a proper cast system so people would refrain from downloading pre-compiled cast systems which may contain malicious code.

File: src/iologindata.cpp (hunk 2 above)
Comment (DSpeichert) [inline src/iologindata.cpp]: SQL injection is worse. `db->escapeString(password)` maybe?

File: schema.sql [hunk 6]
```diff
@@ -330,6 +330,15 @@ CREATE TABLE IF NOT EXISTS `tile_store` (
   FOREIGN KEY (`house_id`) REFERENCES `houses` (`id`) ON DELETE CASCADE
 ) ENGINE=InnoDB;
 
+CREATE TABLE IF NOT EXISTS `live_casts` (
```
Comment (DSpeichert) [inline schema.sql]: I think it would be cleaner to modify `players_online` table to add columns: `cast_password` and `spectator_count` rather than adding a whole new table. If you absolutely think adding a new table is a good idea, it really should be `ENGINE=MEMORY`.

Comment (Milice) [inline schema.sql]: This is actually a very good point, although it would also need a column to check if said player is in fact live casting. Having a separate table looks cleaner but saving a little memory may be worth it in the long run.

And if you're wondering about that extra column; it's for Tibia 11 and Flash client once they become more common, since they would use a webbased authentication and wouldn't be able to smoothly get that information from the engine itself.

Comment (Znote) [inline schema.sql]: > although it would also need a column to check if said player is in fact live casting.

The columns `spectator_count` or `cast_password` could have a null value to represent "cast not active". Etc:
```sql
CREATE TABLE IF NOT EXISTS `players_online` (
  `player_id` int(11) NOT NULL,
  `cast_password` char(16) DEFAULT NULL,
  `cast_spectators` smallint(5) DEFAULT 0,
  PRIMARY KEY (`player_id`)
) ENGINE=MEMORY;
```

null = no cast
empty string = cast without password
string = cast with password

Sample that returns player name that are currently casting and their spectator count:
```sql
SELECT `p`.`name`, `o`.`cast_spectators`
FROM `players_online` AS `o`
INNER JOIN `players` AS `p`
ON `o`.`player_id` = `p`.`id`
WHERE `o`.`cast_password` != 'NULL';
```

Comment (DSpeichert) [inline schema.sql]: Actually hashing that password may not be a good idea in some cases. If you hash it, you can't display the plaintext on a website, which is the main reason why you'd store that password in a database table in the first place (otherwise you can keep it in memory - player cannot cast beyond server's runtime).

Those passwords are temporary (as opposed to account passwords). There is no username to them. By their nature, they are EXPECTED to be shared with other people, which means people would not (re)use their sensitive passwords (which is why we would want to hash them, keeping them somewhat inaccessible even to the server owners). I'm sure people would soon come up with when to share the password on a website (within a guild maybe?). Hashing it makes it forever impossible.

Comment (Znote) [inline schema.sql]: Agrees with @DSpeichert . If we are afraid of noobs using their regular password for casting we can enforce own passwords through random string generation. The user can request a password and password change on his cast, but not explicit decide what that password is as its being generated automatically for security reasons.

**Comment by DamianDEB** [comment]
Djarek and Milice cast not work on tfs 1.2 final release
problem on compilling ^^
i see this system its rlly hard to be work good 🗡 ; D
`Error LIST

Severity Code Description Project File Line Suppression State
Warning C4100 'accountId': unreferenced formal parameter theforgottenserver C:\Users\D\Desktop\Milice\forgottenserver-1.2\src\protocolspectator.cpp 61
Warning C4100 'forced': unreferenced formal parameter theforgottenserver C:\Users\D\Desktop\Milice\forgottenserver-1.2\src\protocolspectator.cpp 158
Warning C4100 'displayEffect': unreferenced formal parameter theforgottenserver C:\Users\D\Desktop\Milice\forgottenserver-1.2\src\protocolspectator.cpp 158
Warning C4100 'broadcast': unreferenced formal parameter theforgottenserver C:\Users\D\Desktop\Milice\forgottenserver-1.2\src\protocolspectator.cpp 296
Error C2039 'getLevelPercent': is not a member of 'Player' theforgottenserver C:\Users\D\Desktop\Milice\forgottenserver-1.2\src\protocolspectator.cpp 2752
Error C2039 'getMagicLevelPercent': is not a member of 'Player' theforgottenserver C:\Users\D\Desktop\Milice\forgottenserver-1.2\src\protocolspectator.cpp 2765

Output

1>..\src\protocolspectator.cpp(61): warning C4100: 'accountId': unreferenced formal parameter
1>..\src\protocolspectator.cpp(158): warning C4100: 'forced': unreferenced formal parameter
1>..\src\protocolspectator.cpp(158): warning C4100: 'displayEffect': unreferenced formal parameter
1>..\src\protocolspectator.cpp(296): warning C4100: 'broadcast': unreferenced formal parameter
1>..\src\protocolspectator.cpp(2752): error C2039: 'getLevelPercent': is not a member of 'Player'
1> c:\users\d\desktop\milice\forgottenserver-1.2\src\npc.h(29): note: see declaration of 'Player'
1>..\src\protocolspectator.cpp(2765): error C2039: 'getMagicLevelPercent': is not a member of 'Player'
1> c:\users\d\desktop\milice\forgottenserver-1.2\src\npc.h(29): note: see declaration of 'Player'

Protocolspectator.cpp
Line 61 - void ProtocolSpectator::login(const std::string& name, uint32_t accountId, OperatingSystem_t operatingSystem)
Line 158 - void ProtocolSpectator::logout(bool displayEffect, bool forced)
Line 296 - void ProtocolSpectator::writeToOutputBuffer(const NetworkMessage& msg, bool broadcast/* = false*/) {
Line 2752 - msg.addByte(player->getLevelPercent());
Line 2765 - msg.addByte(player->getMagicLevelPercent());

Any Solution for this ?
`

File: src/otserv.cpp [hunk 7]
```diff
@@ -237,13 +246,16 @@ void mainLoader(int, char*[], ServiceManager* services)
 	// Game client protocols
 	services->add<ProtocolGame>(g_config.getNumber(ConfigManager::GAME_PORT));
 	services->add<ProtocolLogin>(g_config.getNumber(ConfigManager::LOGIN_PORT));
-
+
```
Comment (MatheusGrilo) [inline src/otserv.cpp]: Best modification

File: schema.sql (hunk 6 above)
Comment (ranisalt) [inline schema.sql]: He might just add an incrementing ID instead. It's not a problem to have holes in the count.
