### ISSUE TITLE
[Bug]: Compilation on Ubuntu 22.04 does not work

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#4943]
### By submitting this bug issue, you agree to the following.

- [x] This is a bug in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository
- [x] This bug has not been resolved in master branch
- [x] There is no existing issue for this bug already

### Does this bug crash tfs?

no

### Server Version

1.7 (Master)

### Operation System

all (listed below), Ubuntu 22.04

### Bug description

tfs::http makes it impossible to compile on Ubuntu 22.04

### Steps to reproduce

1. Try to compile TFS with `cmake --preset default -DHTTP=OFF -DUSE_LUAJIT=ON && cmake --build --config Release --preset default`
2. It fails with errors:
```
/usr/bin/ld: src/Release/libtfslib.a(unity_5_cxx.cxx.o): in function `(anonymous namespace)::mainLoader(ServiceManager*)':
unity_5_cxx.cxx:(.text+0x212b1): undefined reference to `tfs::http::start(std::basic_string_view<char, std::char_traits<char> >, unsigned short, int)'
/usr/bin/ld: src/Release/libtfslib.a(unity_2_cxx.cxx.o): in function `Game::setGameState(GameState_t)':
unity_2_cxx.cxx:(.text+0x16c7a): undefined reference to `tfs::http::stop()'
```

### Actual Behavior

It fails to compile.
It's impossible to compile without `-DHTTP=OFF`, because default boost version on Ubuntu 22.04 is 1.74.
TFS requires 1.75 with `HTTP` and 1.71 without it. With disabled `HTTP`, there is still code that tries to start/stop `tfs::http`, which makes it fail to compile.

### Expected Behavior

It should compile or we should drop Ubuntu 22.04 support.

There are 2 possible fixes:
1. Add `add_definitions(-DHTTP_ENABLED)` in `CMakeLists.txt` and `#ifdef HTTP_ENABLED` in 2 places around `tfs::http` code to make it compile on Ubuntu 22.04
2. Make boost 1.75 default version for TFS. Drop Ubuntu 22.04 support - it will still compile with vcpkg on Ubuntu 22.04, but not with system libraries.

### Backtrace

```cpp

```

**Comment by gesior** [comment]
Fixed by https://github.com/otland/forgottenserver/pull/4876
