### ISSUE TITLE
Missing "-ldl" flag for linker. Cannot compile TFS 0.4 and 1.x on one PC.

### ISSUE THREAD

**Issue by JSkalskiSBG** [otland/forgottenserver#2502]
### Steps to reproduce
1. Download all libraries for TFS 1.x on Debian 8/9. You can compile TFS 1.x.
2. Download all libraries for TFS 0.4/otserv. You still can't compile 0.4. You need to install LUA 5.1 manually.
3. Download LUA 5.1 sources, compile and install. Now you can compile 0.4.
4. Try to compile 1.x again.

### Expected behaviour
TFS 1.x and 0.4 compiles on one PC.

### Actual behaviour
TFS 1.x compilation breaks on linker with error:
> /usr/bin/ld: /usr/local/lib/liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'

### Environment
Debian 8.x, Debian 9.4, Mint 18.1

### Fix
I fixed it by adding:

`set(CMAKE_CXX_STANDARD_LIBRARIES -ldl)`

to **CMakeLists.txt**

Problem is that I got no idea what it does :)
so I won't create PR.

**Anyone knows, if it's proper solution?**

**Comment by ranisalt** [comment]
Did you clean CMake files prior to recompiling? Also we do not support legacy versions.

**Comment by gesior** [comment]
@ranisalt 
I did remove folder 'build' around 50 times on 2 dedics and my local PC. Tried every option.

> 1. Download all libraries for TFS 1.x on Debian 8/9. You can compile TFS 1.x.
I think that there is LUA 5.3 on dedic. Is it overwriten by LUA 5.1?

**Comment by ranisalt** [comment]
I can't understand why the build system is trying to compile against static liblua instead of shared version (liblua.so). Can you provide the command line you used to generate makefile and the one to compile?

**Comment by JSkalskiSBG** [comment]
I use:
> mkdir build && cd build && cmake .. && make -j 12

On forgottenserver without any changes it finishes with error:
https://gist.github.com/JSkalskiSBG/c890ac50be28fe19206ccfd86d45439c

After I add **-ldl** to file **build/CMakeFiles/tfs.dir/link.txt** it passes. Server starts without any errors.

Does it mean that TFS 1.3 works with LUA 5.1, but I got LUA 5.1 build/installed in some uncompatible way?
I had to download 5.1.4 sources, compile and install to make TFS 0.4 work.

**Comment by ranisalt** [comment]
It seems to be the same as awesomeWM/awesome#361 where they say it's a CMake+Lua issue, since static libraries (.a) do not carry dependency information and CMake can't detect it.

You can try to install LuaJIT or remove your static Lua version, since TFS works fine (and frustration-free) with shared libraries.

**Comment by JSkalskiSBG** [comment]
@ranisalt 
Thank you! After installation of LuaJIT I don't need '-ldl' anymore.

If anyone has same problem. List of my installed packages on Linux Mint 18:

> liblua5.1-0/xenial,now 5.1.5-8ubuntu1 amd64 [zainstalowany]
> liblua5.1-0-dev/xenial,now 5.1.5-8ubuntu1 amd64 [zainstalowany]
> liblua5.2-0/xenial,now 5.2.4-1ubuntu1 amd64 [zainstalowany,automatycznie]
> liblua5.2-dev/xenial,now 5.2.4-1ubuntu1 amd64 [zainstalowany]
> liblua5.3-0/xenial,now 5.3.1-1ubuntu2 amd64 [zainstalowany]
> liblua5.3-dev/xenial,now 5.3.1-1ubuntu2 amd64 [zainstalowany]
> libluajit-5.1-2/xenial,now 2.0.4+dfsg-1 amd64 [zainstalowany,automatycznie]
> libluajit-5.1-common/xenial,xenial,now 2.0.4+dfsg-1 all [zainstalowany,automatycznie]
> libluajit-5.1-dev/xenial,now 2.0.4+dfsg-1 amd64 [zainstalowany]
> lua5.1/xenial,now 5.1.5-8ubuntu1 amd64 [zainstalowany]

And then manually compiled and installed LUA 5.1.4.
Only thing I got to do now is to switch 'g++' link target between 'g++-6' and 'g++-4.9' to compile TFS 1.x and TFS 0.4/otserv.

**Comment by ranisalt** [comment]
You should only need to install one of the `-dev` packages, it pulls everything needed as dependencies. The Lua 5.1 version should be polyfilled inside TFS, though.

Also, why exactly did you compile Lua by hand?

**Comment by gesior** [comment]
@ranisalt 
After installation of all libraries needed by TFS 1.3 and TFS 0.4 I could not compile TFS 0.4 and otserv.
I found somewhere hint that I should download some .tar.gz with LUA 5.1.4, compile it and install. Then TFS 0.4 and otserv worked.
