### ISSUE TITLE
getting this error on compiling can you helpme?

### ISSUE THREAD

**Issue by mimusassasin** [otland/forgottenserver#1558]
[  5%] Building CXX object CMakeFiles/tfs.dir/src/otpch.cpp.o
[  6%] Building CXX object CMakeFiles/tfs.dir/src/actions.cpp.o
In file included from /root/tfs/src/actions.h:23:0,
                 from /root/tfs/src/actions.cpp:22:
/root/tfs/src/baseevents.h:30:22: error: \u2018virtual Event::~Event()\u2019 declared virtual cannot be defaulted in the class body
/root/tfs/src/baseevents.h:56:27: error: \u2018virtual BaseEvents::~BaseEvents()\u2019 declared virtual cannot be defaulted in the class body
In file included from /root/tfs/src/actions.cpp:22:0:
/root/tfs/src/actions.h:35:49: error: expected \u2018;\u2019 at end of member declaration
/root/tfs/src/actions.h:35:51: error: \u2018override\u2019 does not name a type
/root/tfs/src/actions.h:36:52: error: expected \u2018;\u2019 at end of member declaration
/root/tfs/src/actions.h:36:54: error: \u2018override\u2019 does not name a type
/root/tfs/src/actions.h:73:36: error: expected \u2018;\u2019 at end of member declaration
/root/tfs/src/actions.h:73:42: error: \u2018override\u2019 does not name a type
/root/tfs/src/actions.h:84:21: error: expected initializer before \u2018:\u2019 token
In file included from /root/tfs/src/item.h:23:0,
                 from /root/tfs/src/bed.h:23,
                 from /root/tfs/src/actions.cpp:23:
/root/tfs/src/cylinder.h:208:29: error: expected initializer before \u2018:\u2019 token
In file included from /root/tfs/src/items.h:25:0,
                 from /root/tfs/src/item.h:25,
                 from /root/tfs/src/bed.h:23,
                 from /root/tfs/src/actions.cpp:23:
/root/tfs/src/itemloader.h:181:16: error: expected declaration before end of line
make[2]: **\* [CMakeFiles/tfs.dir/src/actions.cpp.o] Error 1
make[1]: **\* [CMakeFiles/tfs.dir/all] Error 2
make: **\* [all] Error 2

**Comment by djarek** [comment]
g++4.8 or higher is required to compile TFS (g++ -v to check the version).

**Comment by mimusassasin** [comment]
tank u im instaling ubuntu 14.04 it would fix it?

**Comment by ranisalt** [comment]
Yes. [Travis](https://github.com/otland/forgottenserver/blob/master/.travis.yml) runs on Ubuntu 14.04, so you can run the same commands.

**Comment by marksamman** [comment]
Travis runs on 12.04, so if you use the Travis commands you should be able to compile on 12.04. 14.04 should work if you follow the wiki instructions. We should update the wiki to mention this though.

**Comment by EPuncker** [comment]
I think the wiki has been fixed already?!
https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu
