### PR TITLE
[12.00] Adding support for colored loot

### PR DESCRIPTION
**Pull request by omarcopires**
### Pull Request Prelude

- [ ] I have followed [proper The Forgotten Server code styling][code].
- [ ] I have read and understood the [contribution guidelines][cont] before making this PR.
- [ ] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Items are now displayed with different coloured frames or corners which allows you to identify the approximate value of the item at a glance. Each item is highlighted in the respective colour in the loot message as well. This feature can be disabled in the client options.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

Co-Authored-By: Lucas Prazeres <9704501+LukSrT@users.noreply.github.com>
Co-Authored-By: slavi <slavidodo@gmail.com>

### CODE REVIEW

**Comment by omarcopires** [comment]
> I don't really understand the mechanism behind it. Can any string be sent as colored or just predefined client ids?

It is not necessary to send any external information, the reading of colors is done automatically by a client file. Player can change to check colors based on market price.

0/undefined: No frame and white text;
1-999: Gray
1,000 - 9,999: Green
10,000 - 99,999: Blue
100,000 999,999: Purple
1,000,000+: Yellow

**Comment by Zbizu** [comment]
wait so `{ expensive clientId | any text I want to write }` will make the text purple? Pretty cool

**Comment by omarcopires** [comment]
> wait so will make the text yellow? Pretty cool`{ expensive clientId | any text I want to write }`

It needs to be tested, I only tested it with itemId

**Comment by Zbizu** [comment]
signals confirmed to be working on Canary with 12.71
obraz
```
	n = NetworkMessage()
	n:addByte(0xCD)
	n:addU16(1)
	n:addU16(6529)
	n:addU32(6500000)
	n:sendToPlayer(player)
	player:sendTextMessage(MESSAGE_LOOT, "{6529|test} also {6529|message2}")
```

File: src/game.cpp [hunk 1]
```diff
@@ -4458,6 +4459,33 @@ void Game::loadAccountStorageValues()
...
+	Database& db = Database::getInstance();
+	DBResult_ptr result = db.storeQuery(query.str());
+	if (!result) {
+		return false;
+	}
+
+	do {
+		query2.str(std::string());
+		uint16_t itemId = result->getNumber<uint16_t>("itemtype");
+		query2 << "SELECT AVG(`price`) AS 'price' FROM `market_offers` WHERE `itemtype` = " << itemId << ";";
```
Comment (marmichalski) [inline src/game.cpp:4477]: This can be done in a single query using group by, instead of N+1 where N is itemtypes count.
