### ISSUE TITLE
[Bug]: MySQL Error Message: TLS/SSL error: SSL is required, but the server does not support it

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#4954]
### By submitting this bug issue, you agree to the following.

- [x] This is a bug in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository
- [x] This bug has not been resolved in master branch
- [x] There is no existing issue for this bug already

### Does this bug crash tfs?

no

### Server Version

1.7 (Master)

### Operation System

all (listed below)

### Bug description

Server cannot connect to MySQL on server start

### Possible Pull Requests which are to blame

- #4932 

### Steps to reproduce

1. Compile server with vcpkg
2. Try to run server, it fails on connection to MySQL

It was first time reported here: https://otland.net/threads/server-does-not-open-tls-ssl-problem.290112/
In canary it was fixed in 2024.

I have this problem on Ubuntu and Windows when I compile with vcpkg.

### Actual Behavior

TFS compiled with vcpkg cannot connect to MySQL/MariaDB without SSL

### Expected Behavior

TFS compiled with vcpkg can connect to MySQL/MariaDB without SSL.

### Backtrace

```cpp

```

**Comment by gesior** [comment]
Fix from post:
https://otland.net/threads/server-does-not-open-tls-ssl-problem.290112/#post-2775697
does not work on Linux, if you install `libmysqlclient-dev` (MySQL 8.0), you must install `libmariadb-dev-compat`(MariaDB connector compatible with MySQL 5.7).

If we add that fix, we must update Linux compilation instructions in wikis ex.: https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu

**Comment by alysonjacomin** [comment]
@gesior test build with vcpkg in linux using disable ssl:

bellow:

`tfs::detail::Mysql_ptr handle{mysql_init(nullptr)};`

add:

`uint8_t ssl_disabled = 0;`
`mysql_options(handle.get(), MYSQL_OPT_SSL_VERIFY_SERVER_CERT, &ssl_disabled);`

**Comment by gesior** [comment]
> [@gesior](https://github.com/gesior) test build with vcpkg in linux using disable ssl:
> 
> `uint8_t ssl_disabled = 0;` `mysql_options(handle.get(), MYSQL_OPT_SSL_VERIFY_SERVER_CERT, &ssl_disabled);`
> 
> bellow:
> 
> `detail::Mysql_ptr handle{mysql_init(nullptr)};`

This fixes vcpkg build, as vcpkg uses MariaDB libraries on all systems (Linux/Windows/MacOS).

Problems are Linux builds with system libraries (without vcpkg). Some wikis point to `apt install libmysqlclient-dev` ex. Ubuntu wiki ( https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu ), but it fails to compile.
It works only, if you install `libmariadb-dev-compat` in place of `libmysqlclient-dev`, because `MYSQL_OPT_SSL_VERIFY_SERVER_CERT` is MySQL 5.7/MariaDB constant and default MySQL on Ubuntu 22.04+ and new Linuxes is MySQL 8.0, which deprecated `MYSQL_OPT_SSL_VERIFY_SERVER_CERT` ( https://dev.mysql.com/doc/c-api/5.7/en/mysql-options.html ):
```
This option is deprecated as of MySQL 5.7.11 and is removed in MySQL 8.0. Instead, use MYSQL_OPT_SSL_MODE with a value of SSL_MODE_VERIFY_IDENTITY.
```

Only Arch Linux, Debian and CentOS compilation wikis point to MariaDB library, all other Linux wikis ( https://github.com/otland/forgottenserver/wiki ) point to MySQL library.

**EDIT:**
If we want to implement this, we should drop MySQL 5.7+ support in:
https://github.com/otland/forgottenserver/blob/c519cc6e6f9864e933c8a5a94d20afee538e70de/cmake/FindMySQL.cmake
and allow only MariaDB and MySQL 5.7
or drop MySQL at all. It's possible that last Linux distro with MySQL 5.7 as default, supports 'boost' library older than 1.71, so it cannot compile TFS as all (even with `HTTP` - which requires boost 1.75 - disabled).

**Comment by alysonjacomin** [comment]
I see, but if we stop to analyze this compilation link for Ubuntu it is out of date (for example, it does not contain the installation of "zlib"), when Nekiro added Packet Compression he forgot to update it ...

We need to update these other build methods that don't use vcpkg

**Comment by ranisalt** [comment]
Checkout https://github.com/otland/forgottenserver/pull/4938 and see if using `libmysql` instead of `libmariadb` works. I can't even compile with `libmariadb` because the code is full of errors

**Comment by gesior** [comment]
> Checkout [#4938](https://github.com/otland/forgottenserver/pull/4938) and see if using `libmysql` instead of `libmariadb` works. I can't even compile with `libmariadb` because the code is full of errors

You cannot compile current TFS master? What OS? cmake or VS compiler? with vpckg or without?

**Comment by ranisalt** [comment]
> You cannot compile current TFS master? What OS? cmake or VS compiler? with vpckg or without?

Arch Linux, CMake 4.0.3 with vcpkg. There's an issue within libmariadb where it redefines `bool` using `typedef` but C already has `bool`, this is a super outdated practice that should be guarded by compile time checks

```
Change Dir: '~/.local/share/vcpkg/buildtrees/libmariadb/x64-linux-dbg'

Run Build Command(s): /usr/bin/ninja -v -v -j17 install
[1/85] /usr/bin/cc -DHAVE_OPENSSL -DHAVE_TLS -DLIBICONV_PLUG -DMARIADB_MACHINE_TYPE=\"x86_64\" -DMARIADB_SYSTEM_TYPE=\"Linux\" -I~/Documents/forgottenserver/build/vcpkg_installed/x64-linux/include -I~/.local/share/vcpkg/buildtrees/libmariadb/x64-linux-dbg/include -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/plugins/auth -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/include -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/plugins/auth/ref10 -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/plugins/compress -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/plugins/pvio -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/libmariadb -fPIC -Wunused -Wlogical-op -Wno-uninitialized -Wall -Wextra -Wformat-security -Wno-init-self -Wwrite-strings -Wshift-count-overflow -Wdeclaration-after-statement -Wno-undef -Wno-unknown-pragmas -Wno-stringop-truncation -Werror -g   -D HAVE_COMPRESS -D LIBMARIADB -D THREAD -fPIC -MD -MT libmariadb/CMakeFiles/mariadb_obj.dir/ma_array.c.o -MF libmariadb/CMakeFiles/mariadb_obj.dir/ma_array.c.o.d -o libmariadb/CMakeFiles/mariadb_obj.dir/ma_array.c.o -c ~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/libmariadb/ma_array.c
FAILED: libmariadb/CMakeFiles/mariadb_obj.dir/ma_array.c.o 
/usr/bin/cc -DHAVE_OPENSSL -DHAVE_TLS -DLIBICONV_PLUG -DMARIADB_MACHINE_TYPE=\"x86_64\" -DMARIADB_SYSTEM_TYPE=\"Linux\" -I~/Documents/forgottenserver/build/vcpkg_installed/x64-linux/include -I~/.local/share/vcpkg/buildtrees/libmariadb/x64-linux-dbg/include -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/plugins/auth -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/include -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/plugins/auth/ref10 -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/plugins/compress -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/plugins/pvio -I~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/libmariadb -fPIC -Wunused -Wlogical-op -Wno-uninitialized -Wall -Wextra -Wformat-security -Wno-init-self -Wwrite-strings -Wshift-count-overflow -Wdeclaration-after-statement -Wno-undef -Wno-unknown-pragmas -Wno-stringop-truncation -Werror -g   -D HAVE_COMPRESS -D LIBMARIADB -D THREAD -fPIC -MD -MT libmariadb/CMakeFiles/mariadb_obj.dir/ma_array.c.o -MF libmariadb/CMakeFiles/mariadb_obj.dir/ma_array.c.o.d -o libmariadb/CMakeFiles/mariadb_obj.dir/ma_array.c.o -c ~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/libmariadb/ma_array.c
In file included from ~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/libmariadb/ma_array.c:23:
~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/include/ma_global.h:687:25: error: ‘bool’ cannot be defined via ‘typedef’
  687 | typedef char            bool;   /* Ordinary boolean values 0 1 */
      |                         ^~~~
~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/include/ma_global.h:687:25: note: ‘bool’ is a keyword with ‘-std=c23’ onwards
~/.local/share/vcpkg/buildtrees/libmariadb/src/v3.4.5-e8c0c6b762.clean/include/ma_global.h:687:1: error: useless type name in empty declaration [-Werror]
  687 | typedef char            bool;   /* Ordinary boolean values 0 1 */
      | ^~~~~~~
cc1: all warnings being treated as errors
```

**Comment by gesior** [comment]
> Arch Linux, CMake 4.0.3 with vcpkg.

I tried it in docker and build fails on Arch with vcpkg.
It will probably fail on all OSes with gcc 15 that supports C++ 23:
https://gcc.gnu.org/gcc-15/porting_to.html#c23-new-keywords
I will try to compile it on Ubuntu 25.04 with g++ 15. Then I will check commit with mysql/mariadb selection.

**Edit:**
I tried to compile on Ubuntu 25.10 with g++ 15 and it failed the same way.

**Comment by Tofame** [comment]
When I heard it started happening to users, also happened to me while using another engine I did what canary did:
`mysql_options(handle, MYSQL_OPT_SSL_VERIFY_SERVER_CERT, &ssl_enabled);`
I'd say the ssl_enabled boolean, could be taken from config.lua. So users have option to either disable it (for example on localhost) or have it enabled if they wish.

**Comment by gesior** [comment]
> MYSQL_OPT_SSL_VERIFY_SERVER_CERT

`MYSQL_OPT_SSL_VERIFY_SERVER_CERT` this line won't compile with "MySQL 8.0 connection library" :(

MariaDB library from vcpkg does not compile on new compilers (C++23).

Probably final solution will be to merge https://github.com/otland/forgottenserver/pull/4938 (requires more testing) and add this line `mysql_options(handle, MYSQL_OPT_SSL_VERIFY_SERVER_CERT, &ssl_enabled);` with some library type or library version verification (random version of libraries in examples, it must be tested on multiple OSes with and without vcpkg):
```cpp
#if defined(MARIADB_VERSION_ID)
  #if MARIADB_VERSION_ID < 10000*3 + 100*1 + 0
(...)
#elif defined(MYSQL_VERSION_ID)
  #if MYSQL_VERSION_ID < 50700
(...)
```

**Comment by Tofame** [comment]
> `MYSQL_OPT_SSL_VERIFY_SERVER_CERT` this line won't compile with "MySQL 8.0 connection library" :(

Try from https://dev.mysql.com/doc/c-api/8.0/en/mysql-options.html
MYSQL_OPT_SSL_MODE with value SSL_MODE_DISABLED

They do differ, mariaDB and mssql, so ye, there will be #if definitions needed.

**Comment by Zbizu** [comment]
This is what worked for me on MariaDB 3.4.5. I'm not sure if it's compatible with libmysql.
The issue can be reproduced locally by trying to connect the server to a database hosted on xampp.

```diff
diff --git a/config.lua.dist b/config.lua.dist
index 2206b5171..e09a212cd 100644
--- a/config.lua.dist
+++ b/config.lua.dist
@@ -115,6 +115,7 @@ mysqlPass = ""
 mysqlDatabase = "ots"
 mysqlPort = 3306
 mysqlSock = ""
+mysqlForceSSL = false
 
 -- Misc.
 -- NOTE: classicAttackSpeed set to true makes players constantly attack at regular
diff --git a/src/configmanager.cpp b/src/configmanager.cpp
index 734e36be1..3b6aa4fc4 100644
--- a/src/configmanager.cpp
+++ b/src/configmanager.cpp
@@ -184,6 +184,7 @@ bool ConfigManager::load(bool isReload)
 		string[MYSQL_SOCK] = getGlobalString(L, "mysqlSock", "");
 		string[MYSQL_CERT] = getGlobalString(L, "mysqlCert", "");
 		integer[SQL_PORT] = getGlobalNumber(L, "mysqlPort", 3306);
+		boolean[MYSQL_FORCE_SSL] = getGlobalBoolean(L, "mysqlForceSSL", false);
 
 		// central database
 		string[CENTRAL_HOST] = getGlobalString(L, "centralHost", "");
diff --git a/src/configmanager.h b/src/configmanager.h
index eaf81d7db..de72fe407 100644
--- a/src/configmanager.h
+++ b/src/configmanager.h
@@ -61,6 +61,8 @@ class ConfigManager
 			PREY_ALLOW_MULTIPLE_LIST,
 			PRODUCTION_MODE,
 			LEGACY_LOGIN_PROTOCOL,
+			MYSQL_FORCE_SSL,
+
 			LAST_BOOLEAN_CONFIG // this must be the last one
 		};
 
diff --git a/src/database.cpp b/src/database.cpp
index 78931dde6..78616ddec 100644
--- a/src/database.cpp
+++ b/src/database.cpp
@@ -7,6 +7,7 @@
 #include "configmanager.h"
 #include "tasks.h"
 
+#include <mysql/mysql.h>
 #include <mysql/errmsg.h>
 
 extern ConfigManager g_config;
@@ -23,6 +24,11 @@ static Mysql_ptr connectToDatabase(const bool retryIfError, DBConfig cfg)
 
 	isFirstAttemptToConnect = false;
 
+	// mariadb options in case ssl is disabled
+	my_bool ssl_enforce = 0;
+	my_bool ssl_verify = 0;
+	unsigned int ssl_mode = 0;
+
 	// connection handle initialization
 	Mysql_ptr handle{mysql_init(nullptr)};
 	if (!handle) {
@@ -31,6 +37,14 @@ static Mysql_ptr connectToDatabase(const bool retryIfError, DBConfig cfg)
 		goto error;
 	}
 
+	// this fixes connection issues in new versions of mariadb
+	if (!g_config.getBoolean(ConfigManager::MYSQL_FORCE_SSL)) {
+		mysql_options(handle.get(), MYSQL_OPT_SSL_ENFORCE, &ssl_enforce);
+		mysql_options(handle.get(), MYSQL_OPT_SSL_VERIFY_SERVER_CERT, &ssl_verify);
+		mysql_options(handle.get(), MYSQL_OPT_SSL_ENFORCE, &ssl_mode);
+		mysql_ssl_set(handle.get(), nullptr, nullptr, nullptr, nullptr, nullptr);
+	}
+
 	// connect to database
 	if (!mysql_real_connect(
 	        handle.get(), cfg.addr.c_str(), cfg.user.c_str(), cfg.pass.c_str(),
```

**Comment by gesior** [comment]
> This is what worked for me on MariaDB 3.4.5. I'm not sure if it's compatible with libmysql. The issue can be reproduced locally by trying to connect the server to a database hosted on xampp.
> 
> diff --git a/config.lua.dist b/config.lua.dist
> index 2206b5171..e09a212cd 100644
> --- a/config.lua.dist
> +++ b/config.lua.dist
> @@ -115,6 +115,7 @@ mysqlPass = ""
>  mysqlDatabase = "ots"
>  mysqlPort = 3306
>  mysqlSock = ""
> +mysqlForceSSL = false
>  
>  -- Misc.
>  -- NOTE: classicAttackSpeed set to true makes players constantly attack at regular
> diff --git a/src/configmanager.cpp b/src/configmanager.cpp
> index 734e36be1..3b6aa4fc4 100644
> --- a/src/configmanager.cpp
> +++ b/src/configmanager.cpp
> @@ -184,6 +184,7 @@ bool ConfigManager::load(bool isReload)
>  		string[MYSQL_SOCK] = getGlobalString(L, "mysqlSock", "");
>  		string[MYSQL_CERT] = getGlobalString(L, "mysqlCert", "");
>  		integer[SQL_PORT] = getGlobalNumber(L, "mysqlPort", 3306);
> +		boolean[MYSQL_FORCE_SSL] = getGlobalBoolean(L, "mysqlForceSSL", false);
>  
>  		// central database
>  		string[CENTRAL_HOST] = getGlobalString(L, "centralHost", "");
> diff --git a/src/configmanager.h b/src/configmanager.h
> index eaf81d7db..de72fe407 100644
> --- a/src/configmanager.h
> +++ b/src/configmanager.h
> @@ -61,6 +61,8 @@ class ConfigManager
>  			PREY_ALLOW_MULTIPLE_LIST,
>  			PRODUCTION_MODE,
>  			LEGACY_LOGIN_PROTOCOL,
> +			MYSQL_FORCE_SSL,
> +
>  			LAST_BOOLEAN_CONFIG // this must be the last one
>  		};
>  
> diff --git a/src/database.cpp b/src/database.cpp
> index 78931dde6..78616ddec 100644
> --- a/src/database.cpp
> +++ b/src/database.cpp
> @@ -7,6 +7,7 @@
>  #include "configmanager.h"
>  #include "tasks.h"
>  
> +#include <mysql/mysql.h>
>  #include <mysql/errmsg.h>
>  
>  extern ConfigManager g_config;
> @@ -23,6 +24,11 @@ static Mysql_ptr connectToDatabase(const bool retryIfError, DBConfig cfg)
>  
>  	isFirstAttemptToConnect = false;
>  
> +	// mariadb options in case ssl is disabled
> +	my_bool ssl_enforce = 0;
> +	my_bool ssl_verify = 0;
> +	unsigned int ssl_mode = 0;
> +
>  	// connection handle initialization
>  	Mysql_ptr handle{mysql_init(nullptr)};
>  	if (!handle) {
> @@ -31,6 +37,14 @@ static Mysql_ptr connectToDatabase(const bool retryIfError, DBConfig cfg)
>  		goto error;
>  	}
>  
> +	// this fixes connection issues in new versions of mariadb
> +	if (!g_config.getBoolean(ConfigManager::MYSQL_FORCE_SSL)) {
> +		mysql_options(handle.get(), MYSQL_OPT_SSL_ENFORCE, &ssl_enforce);
> +		mysql_options(handle.get(), MYSQL_OPT_SSL_VERIFY_SERVER_CERT, &ssl_verify);
> +		mysql_options(handle.get(), MYSQL_OPT_SSL_ENFORCE, &ssl_mode);
> +		mysql_ssl_set(handle.get(), nullptr, nullptr, nullptr, nullptr, nullptr);
> +	}
> +
>  	// connect to database
>  	if (!mysql_real_connect(
>  	        handle.get(), cfg.addr.c_str(), cfg.user.c_str(), cfg.pass.c_str(),

It should not be configurable ON/OFF, as we do not have real SSL config (cert files etc.) - we can use ON/OFF for compatibility tests.
We expect and want MySQL connection to work without SSL.
We disable it with these extra lines, because some libraries/MySQL-MariaDB servers enabled some SSL by default.

Before any PR/merge, we got to test it with mysql and mariadb libs on some Linux ex. Ubuntu 24.04 and with vcpkg on Windows.
Biggest problem is that, we cannot just 'build' app in ex. docker, we got to run TFS, to detect, if it fails to connect to database.
Merging this PR https://github.com/otland/forgottenserver/pull/4959 would make it easier for Linux. Windows vcpkg build with MariaDB/MySQL databases still must be tested manually.

**Comment by Tofame** [comment]
I said it should be configurable with the assumption default will be OFF @gesior

**Comment by alysonjacomin** [comment]
@gesior From what I understand, the problem we have is only related to Docker, right ?

**Comment by Zbizu** [comment]
@gesior 
my diff is already using `mysql_ssl_set`, all it needs to support ssl is forwarding arguments to it - either from config.lua or from env variables

https://mariadb.com/docs/connectors/mariadb-connector-c/api-functions/mysql_ssl_set

**Comment by gesior** [comment]
> From what I understand, the problem we have is only related to Docker, right ?

No. I have this problem, when I compile on Windows using vcpkg and connect to MariaDB-10.4.32 installed with XAMPP.
Problem is in Docker/on Linux, only if you compile with vcpkg. With Linux system libraries it works fine - I must test it with mysql connector and mariadb connector.

**Comment by Codinablack** [comment]
What I don't understand is how this is a TFS issue?

The problem comes from your own configuration/setup of the mysql database server and is quickly resolved by actually enabling SSL. I get users complaining about this all the time, mostly xampp users, my uniserver users get no problems at all.

I actually just ran into this issue working for someone else, just last night... and all I did was properly configure the database server... there are no changes that need to be done to the game server... SSL is preferred, and if they are trying to force users to use it, then I say, let them! We should be on that same mindset...

Just my own opinion. Take or leave it.... but I truly believe this is not a TFS issue.

**Comment by gesior** [comment]
I want TFS 1.8 to be 'download & run' app. Like OTSes were years ago.
Not download, read 100 pages of database/whatever documentation and run.

> The problem comes from your own configuration/setup of the mysql database server and is quickly resolved by actually enabling SSL.

If problem comes from default TFS and database configuration, it's TFS problem.
We can fix it in code or edit all Wiki compilation tutorials ( https://github.com/otland/forgottenserver/wiki ), to make it use library that works.
Right now we have problem with all `vcpkg` builds and Linux/XAMPP default database configs.

> SSL is preferred, and if they are trying to force users to use it, then I say, let them!

Why? 100% of OTSes run OTS and database on same host. Why would we force SSL configuration? If you can capture loopback network packets (`127.0.0.1`), you probably already have access to SSL cert and SQL password on that host.

We are seriously thinking about running TFS inside docker ( https://github.com/otland/forgottenserver/pull/4959 ), so it must build with system libraries. Nobody will wait 20-40 minutes to compile all vcpkg libraries inside docker.

> quickly resolved by actually enabling SSL

**Please post tutorial how to do it on XAMPP here:**
https://otland.net/threads/server-does-not-open-tls-ssl-problem.290112/
It may help a lot of people, who can't update and recompile their engines.

**Comment by Codinablack** [comment]
> If problem comes from default TFS and database configuration, it's TFS problem.

No it's not!
All you did there was group two things that are not the same, together! 
You simply used grammar to point the problem back at TFS... that's it! 

The problem is not at all with TFS! TFS has no problems! The problem ONLY comes from THE database server, and is completely and utterly fixed WITHOUT TOUCHING TFS AT ALL... and as I previously mentioned, if you are using uniserver instead of xampp, the problem doesn't even exist at all! So how can this be a TFS problem???????

You say "if problem comes from default tfs" it doesn't...
You say "if problem comes from default tfs AND datbase configuration"... they are not the same? The way you configure your database server has absolutely nothing to do with TFS!


> Why? 100% of OTSes run OTS and database on same host

Who the hell are you to be such an authority on what 100 PERCENT OF THE OT'S ARE DOING? 

This is the second time you have came here, claiming to be the godfather of all OT knowledge and have some sort of personal relationship or overview with every single OT server in existence... stop it! Just stop! You can't possibly know what every single OT server is doing, so stop making such claims, they don't serve to strengthen your position, they simply demonstrate that you think you know everything about everything, even things you couldn't possibly know... so yeah, these comments completely weaken your position, not strengthen it.

Connecting to your server via SSL IS BEST PRACTICE! Hence the reason it is trying to FORCE YOU TO DO SO!

I will say one more time before I leave to avoid being sucked into an endless and pointless debate with gesior...

THIS IS NOT A TFS PROBLEM!

Same as how what is going on for OTC is not a TFS problem.
Same as how a persons personal changes to their own server is not a TFS problem.
Same as the scripts a person uses for setting up their own server is not a TFS problem..
Same as how a problem with proxies in someone's setup... IS NOT A TFS PROBLEM.

Over the years, I have watched MANY issues arise on this repo, all closely tied to TFS, but because they weren't actually directly from TFS code itself causing the issue, it's always been dismissed as not TFS's responsibility.... and THIS, THIS IS THE PENTACLE OF EXAMPLES FOR THINGS THAT ARE NOT TFS'S PROBLEM!

**Comment by Zbizu** [comment]
The problem appears to be mariadb specific. I had no issues with connection when running libmysql.
On the other hand, I wasn't able to build my suggested code with libmysql as these lines are mariadb specific.

To detect if the build is using mariadb, I used the following line:
`#ifdef MARIADB_VERSION_ID`

this is how I got it working in my private repo:
```cpp
static Mysql_ptr connectToDatabase(const bool retryIfError, DBConfig cfg)
{
	bool isFirstAttemptToConnect = true;

retry:
	if (!isFirstAttemptToConnect) {
		std::this_thread::sleep_for(std::chrono::seconds(1));
	}

	isFirstAttemptToConnect = false;

	// this fixes connection issues in new versions of mariadb
#ifdef MARIADB_VERSION_ID
	bool ssl_enforce = 0;
	bool ssl_verify = 0;
	unsigned int ssl_mode = 0;
#endif

	// connection handle initialization
	Mysql_ptr handle{mysql_init(nullptr)};
	if (!handle) {
		console::printResult(CONSOLE_LOADING_ERROR);
		reportError("Failed to initialize MySQL connection handle.");
		goto error;
	}

	// this fixes connection issues in new versions of mariadb
#ifdef MARIADB_VERSION_ID
	if (!g_config.getBoolean(ConfigManager::MYSQL_FORCE_SSL)) {
		mysql_options(handle.get(), MYSQL_OPT_SSL_ENFORCE, &ssl_enforce);
		mysql_options(handle.get(), MYSQL_OPT_SSL_VERIFY_SERVER_CERT, &ssl_verify);
		mysql_options(handle.get(), MYSQL_OPT_SSL_ENFORCE, &ssl_mode);
		mysql_ssl_set(handle.get(), nullptr, nullptr, nullptr, nullptr, nullptr);
	}
#endif

	// connect to database
	if (!mysql_real_connect(
	        handle.get(), cfg.addr.c_str(), cfg.user.c_str(), cfg.pass.c_str(),
			cfg.name.c_str(), cfg.port, cfg.sock.c_str(), 0)) {
		reportError("MySQL: " + std::string(mysql_error(handle.get())));
		goto error;
	}
	return handle;

error:
	if (retryIfError) {
		goto retry;
	}

	return nullptr;
}
```

@gesior if you don't want to introduce a new config value, that block may be included without that "if" statement and it should solve the problem without changing anything in the default behaviour

@Codinablack please keep the discussion civil. We are here to solve the problem, not to fight each other.
