### ISSUE TITLE
Live cast system [$205]

### ISSUE THREAD

**Issue by Znote** [otland/forgottenserver#984]
# Live Cast System

twifysoft.net has a very good cast system, but I understand if they wish to keep the sources closed. 
However, I believe a good live cast system will help the growth of this community, and motivate more people to jump on projects based on this repository. 

**So I want a live cast system, on this official repository.**
## How I want it to work (copied from twifysoft):
- You can start casting by typing the command !cast ingame. 
- You can also start casting with a password, by using the command !cast password. 
- Login to the server without account name to watch a live cast. 
- If the cast has a password, enter the password in the password login field (still empty account name).
- An in-game cast group chat channel. If the caster has the channel open, it is considered enabled, if caster is not in the channel its considered disabled. 
## Code quality guidelines:

[@marksamman](https://github.com/otland/forgottenserver/issues/294#issuecomment-30718539):
- The use of the dispatcher thread must be minimal (viewers should receive a copy of the packets sent to the caster in asio thread). 
- All caster variables must be stored in (or in another object referenced from) the ProtocolGame instance of the caster player.

I will be the first here to take initiative and use Bountysource, I hope more people will follow. :+1: 
##

**Comment by rowaraujo** [comment]
If I publish my system, I get how much?

**Comment by EPuncker** [comment]
if it fulfills all @marksamman requirements you may get the bounty I guess

**Comment by Znote** [comment]
@marksamman @djarek Not sure whats going on with the bountysource integration, but I chipped in some extra bucks raising this from $170 to $205.

**Comment by ranisalt** [comment]
@Znote it's working.
`There is a $205 open bounty on this issue. Add to the bounty at Bountysource.`

**Comment by gugahoa** [comment]
Isn't @djarek system already done and working? Most of the people that shows up with errors are using it with modifications

**Comment by Znote** [comment]
@ranisalt I edited that myself manually, the title still says $170 and it appears I cannot change that. 

@gugahoa There is a pull request by djarek, but it hasn't been accepted and merged yet by Marksamman. Last thing I read there are some dodgy code in the shadows of this request that need some work for the sake of this request, as well as some good testers who know how to use a debugger. 

I don't care if a pull request is working, it has to be merged to master or the bounty still stands.

**Comment by marksamman** [comment]
There seems to be an issue with the Bountysource integration. I've tried re-enabling it without any success, until we figure it out, people interested in bounties should check the Bountysource page for the project for accurate information on bounties. As for the pull request, I'm still waiting to hear from people how well it works without additional modifications to the source code. I don't have a server with enough activity to test it myself.

**Comment by DamianDEB** [comment]
Djarek and Milice cast not work on tfs 1.2 final release 
problem on compilling ^^
i see this system its rlly hard to be work good Djarek start ur project on 2014 🗡 ; D

`1>..\src\protocolgame.cpp(44): error C2143: syntax error: missing ';' before '*'
1>..\src\protocolgame.cpp(44): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>..\src\protocolgame.cpp(1004): error C2065: 'InstantSpell': undeclared identifier
1>..\src\protocolgame.cpp(1004): error C2065: 'instantSpell': undeclared identifier
1>..\src\protocolgame.cpp(1004): error C2227: left of '->getInstantSpell' must point to class/struct/union/generic type
1>  ..\src\protocolgame.cpp(1004): note: type is 'int *'
1>..\src\protocolgame.cpp(1005): error C2065: 'instantSpell': undeclared identifier
1>  protocolold.cpp
1>..\src\protocolspectator.cpp(61): warning C4100: 'accountId': unreferenced formal parameter
1>..\src\protocolspectator.cpp(158): warning C4100: 'forced': unreferenced formal parameter
1>..\src\protocolspectator.cpp(158): warning C4100: 'displayEffect': unreferenced formal parameter
1>..\src\protocolspectator.cpp(296): warning C4100: 'broadcast': unreferenced formal parameter
1>..\src\protocolspectator.cpp(2752): error C2039: 'getLevelPercent': is not a member of 'Player'
1>  c:\users\d\desktop\milice\forgottenserver-1.2\src\npc.h(29): note: see declaration of 'Player'
1>..\src\protocolspectator.cpp(2765): error C2039: 'getMagicLevelPercent': is not a member of 'Player'
1>  c:\users\d\desktop\milice\forgottenserver-1.2\src\npc.h(29): note: see declaration of 'Player'`

**Comment by Znote** [comment]
@djarek 
> I'll resubmit a new pull request when I rebase. This PR has way too many spam messages.

Could you give a status on this?

**Comment by djarek** [comment]
@Znote 
I want to merge #2010 before the casting system so that the latter uses the API rather than push redundant stuff into the database.

**Comment by slavidodo** [comment]
@Znote I will be start working on this very soon!

**Comment by Flyckks** [comment]
I'm going to start working on it.
